extends:
  # - plugin:vue-libs/recommended
  - airbnb
env:
  browser: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
# plugins:
  # - flowtype-errors
rules:
  class-methods-use-this: off
  # flowtype-errors/show-errors: error
  # flowtype-errors/enforce-min-coverage: [warn, 50]
overrides:
  files:
    - '**/*.test.js'
    - '**/__mocks__/*.js'
  env:
    jest: true
  rules:
    function-paren-newline: ["error", "multiline"]
    global-require: off
    import/no-extraneous-dependencies: off
    import/prefer-default-export: off
