language: node_js
node_js:
  - node
  - lts/*
services:
  - mongodb
before_script:
  - cp config/config.stub.json config/config.json
  - cp config/server.mongodb.json config/server.json
script:
  - yarn lint
  - yarn build
  - yarn test -- --coverage --coverageReporters lcov
after_success:
  - if [ "${TRAVIS_NODE_VERSION}" = "node" ]; then cat ./coverage/lcov.info | coveralls; fi
before_deploy:
  - rm -rf public/assets
  - cp public/index.html public/404.html
  - echo $CNAME > public/CNAME
  - node scripts/genFirebaseConfig.js > config/config.json
  - NODE_ENV=producion yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
    condition: $TRAVIS_NODE_VERSION = node
after_deploy:
  - firebase deploy --project prod --token $FIREBASE_CI_TOKEN
