language: node_js
node_js:
  - node
  - lts/*
services:
  - mongodb
before_script:
  - cp config/config.stub.json config/config.json
  - cp config/server.mongodb.json config/server.json
script:
  - yarn lint
  - yarn test -- --coverage --coverageReporters lcov
  - yarn build
after_success:
  - if [ "${TRAVIS_NODE_VERSION}" = "node" ]; then cat ./coverage/lcov.info | coveralls; fi
before_deploy:
  - rm -rf public/assets
  - node scripts/genFirebaseConfig.js > config/config.json
  - NODE_ENV=producion yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_CI_TOKEN
  project: prod
  on:
    branch: master
    condition: $TRAVIS_NODE_VERSION = node
